apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    podGroup: "A"
    minAvailable: "1"
spec:
  schedulerName: my-scheduler
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        example.com/foo: 1
      limits:
        example.com/foo: 1
    