scheduler:
  name: my-scheduler 
  image: mike911209/my-scheduler:latest
  imagePullPolicy: Always
  replicaCount: 1
  leaderElect: false

plugins:
  enabled: ["CustomScheduler"]

pluginConfig:
- name: CustomScheduler
  args:
    mode: Least